name: PHP Linting (Pint)
on:
  workflow_dispatch:
#  push:
#    branches-ignore:
#      - 'dependabot/npm_and_yarn/*'
#      - 'dependabot/composer/*'
  pull_request:
    types: [ opened ]
jobs:
  Pint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39

      - name: Laravel Pint Action
        uses: sergotail/laravel-pint-action@v2.0.0
        with:
          onlyFiles: ${{ steps.changed-files.outputs.all_changed_files }}
          testMode: true
          verboseMode: true
          configPath: ./pint.json
          preset: laravel
          onlyDirty: false
          annotate: true
          pintVersion: 1.8.0
          annotateVersion: 1.8.5
          useComposer: true